env:
  SEGMENT_CONTEXTS: aws-credentials,snyk
  SEGMENT_BUILDKITE_IMAGE: buildkite-agent:latest
steps:
  - label: ":brain: Everything"
    agents:
      queue: v1
    commands: |
      echo '--- Ensuring pip is installed'
      /usr/bin/python3 -m ensurepip --upgrade
      
      echo '--- installing pip version'
      /usr/bin/python3 -m pip install pip==20.2.4

      echo '--- Installing dependencies'
      /usr/bin/python3 -m pip install -r requirements.txt
      /usr/bin/python3 -m pip install --index-url=https://packagecloud.io/segment/py-wheels/pypi/simple segment_source==0.28.0
             
      echo '--- Building package'
      sh build.sh

      echo '--- Publishing package'
      sh publish.sh
    plugins:
      - docker#v3.13.0:
          image: python:3.10.0