env:
  SEGMENT_CONTEXTS: aws-credentials,snyk
  SEGMENT_BUILDKITE_IMAGE: sources-build-python:v1.2.0

steps:
  - label: "Installing dependencies"
    command: pip3 install --extra-index-url=https://packagecloud.io/segment/py-wheels/pypi/simple -r requirements.txt

  - label: "Running tests"
    command: make test

  - label: "Building package"
    command: |
      tag=$(git tag --points-at HEAD)
      if [ -n "$tag" ]; then
        ver=$(python3 setup.py --version)
        name=$(python3 setup.py --name)
        if [ "$tag" == "v$ver" ]; then
          rm -fr ./dist/
          python3 setup.py sdist
        else
          echo "git tag doesn't match package version ($tag != v$ver)"
          exit 1
        fi
      else
        echo "skipping (no tag)"
      fi

  - label: "Publishing package"
    command: |
      if [ -n "$(git tag --points-at HEAD)" ]; then
        ver=$(python3 setup.py --version)
        name=$(python3 setup.py --name)
        package_cloud push segment/py-wheels/python dist/${name}-${ver}.tar.gz
      else
        echo "skipping (no tag)"
      fi