env:
  SEGMENT_CONTEXTS: aws-credentials,snyk
  SEGMENT_BUILDKITE_IMAGE: buildkite-agent:latest
steps:
  - label: ":brain: Everything"
    agents:
      queue: v1
    commands: |
      echo '--- Downloading get-pip.py'
      curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py

      echo '--- Installing pip'
      /usr/bin/python3 get-pip.py

      echo '--- Installing pip version'
      /usr/bin/python3 -m pip install pip==20.2.4

      echo '--- Installing dependencies'
      /usr/bin/python3 -m pip install -r requirements.txt
      /usr/bin/python3 -m pip install --index-url=https://packagecloud.io/segment/py-wheels/pypi/simple segment_source==v0.27.0
             
      echo '--- Building package'
      sh build.sh

      echo '--- Publishing package'
      sh publish.sh
    plugins:
      - docker#v3.13.0:
          image: python:3.10.0