env:
  SEGMENT_CONTEXTS: aws-credentials,snyk
  SEGMENT_BUILDKITE_IMAGE: buildkite-agent:latest
steps:
  - label: ":brain: Build Package"
    agents:
      queue: v1
    artifact_paths:
      - "dist/*"
    commands: |
      echo '--- Downloading get-pip.py'
      curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py

      echo '--- Installing pip'
      /usr/bin/python3 get-pip.py

      echo '--- Installing pip version'
      /usr/bin/python3 -m pip install pip==20.2.4

      echo '--- Installing dependencies'
      /usr/bin/python3 -m pip install -r requirements.txt
      /usr/bin/python3 -m pip install --index-url=https://packagecloud.io/segment/py-wheels/pypi/simple segment_source==v0.27.0
             
      echo '--- Building package'
      sh build.sh

    plugins:
      - docker#v3.13.0:
          image: python:3.9.6

  - wait: ~

  - label: ":brain: Publish Package"
    if: build.branch == "master"
    commands:
        - gem install fpm package_cloud
        - buildkite-agent artifact download "dist/*" .
        - chmod +x ./dist/*
        - sh publish.sh
    plugins:
      - docker#v3.3.0:
              image: ruby:3.2
              environment:
                # required to download the artifacts from s3
                - AWS_REGION
                - AWS_DEFAULT_REGION
                - AWS_ACCESS_KEY_ID
                - AWS_SECRET_ACCESS_KEY
                - AWS_SESSION_TOKEN
                # required by the makefile to properly tag and build
                - BUILDKITE_BUILD_NUMBER
                # required to publish to packagecloud.io
                - PACKAGECLOUD_TOKEN